version: "3.8"

services:
  ocsinventory:
    image: ocsinventory/ocsinventory-docker-image:2.8
    container_name: ocsinventory
    restart: always
    ports:
      - 90:80
      - 443:443
    volumes:
      - "/var/docker/ocsinventory-server/data:/var/docker/ocsinventory-server/data_ocsinventory"
    environment:
      OCS_DB_SERVER: ${OCS_DB_SERVER}
      OCS_DB_USER: ${OCS_DB_USER}
      OCS_DB_PASS: ${OCS_DB_PASS}
      OCS_DB_NAME: ${OCS_DB_NAME}
    depends_on:
      - mysql
      
  mysql:
    image: mysql:8.0.25
    container_name: mysql
    hostname: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - "/var/docker/mysql-server/data:/var/docker/mysql-server/data_mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      entrypoint:
        sh -c "echo 'CREATE DATABASE IF NOT EXISTS glpidb; CREATE USER glpi_user@localhost; GRANT ALL PRIVILEGES ON glpidb.* TO glpi_user@% IDENTIFIED BY glpi; FLUSH PRIVILEGES;' > /docker-entrypoint-initdb.d/init.glpidb.sql;
        /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
      
   glpi_project:
    image: diouxx/glpi
    container_name: glpi_project
    ports:
      - "80:80"
    depends_on:
      - mysql
    environment:
      - TIMEZONE=Europe/Brussels
    volumes:
      - "/var/www/html/glpi/data:/var/www/html/data_glpi"
     restart: always
