version: "1.26"

services:
  OpenVPN:
    image: kylemanna/openvpn:2.4
    container_name: OpenVPN
    ports: 
      - "443:1194/UDP"
    volumes:
      - "/var/docker/openvpn/data:/var/data_openvpn"
    restart: always
